version: '3'
services:
  satellite:
    image: lightstep/collector:latest
    environment:
      - COLLECTOR_API_KEY=eyJhbGciOiJIUzI1NiIsImtpZCI6IjIwMTktMDMtMDEiLCJ0eXAiOiJKV1QifQ.eyJzY29wZSI6eyJjb2xsZWN0b3IiOnsicmVhZHdyaXRlIjp0cnVlfX0sImF1ZF9pZCI6Iml1dnU2dGpxbG9ua3c3dXNmYzRuc24zY3VjcGNob2FqcnZzenRmaTRrbHZoYWprNSIsImF1ZCI6IkV2YWxfU0VfRm9ycmVzdEsiLCJleHAiOjE2MDU4NTUwNTYsImp0aSI6InBydTJnYmcycG9ma25xeHZjaHNuNXpvY2JxM2Q0NTR4cGhmcHhwMjY2cTR5cmV1ciIsImlhdCI6MTU3NDMxOTA1NiwiaXNzIjoibGlnaHRzdGVwLmNvbSJ9.haPF822ijlAKY9D3VpAmUaMtkDcZb03WZJ3dfOgP7H0
      - COLLECTOR_BABYSITTER_PORT=8000 
      - COLLECTOR_ADMIN_PLAIN_PORT=8180
      - COLLECTOR_HTTP_PLAIN_PORT=8182
      - COLLECTOR_HTTP_SECURE_PORT=8183 
      - COLLECTOR_REPORTER_BYTES_PER_PROJECT=1000000000
    ports:
      - "8000:8000" #Diagnostics
      - "8180:8180" #COLLECTOR_ADMIN_PLAIN_PORT, Required for health checks
      - "8182:8182" #COLLECTOR_HTTP_PLAIN_PORT,  Unsecure traffic, or secure traffic that terminates it's secure status before it his the satellite
      - "8183:8183" #COLLECTOR_HTTP_SECURE_PORT, for Secure traffic

