version: '3'
services:
  satellite:
    image: lightstep/collector:latest
    environment:
      - COLLECTOR_API_KEY=eyJhbGciOiJIUzI1NiIsImtpZCI6IjIwMTktMDMtMDEiLCJ0eXAiOiJKV1QifQ.eyJzY29wZSI6eyJjb2xsZWN0b3IiOnsicmVhZHdyaXRlIjp0cnVlfX0sImF1ZF9pZCI6Iml1dnU2dGpxbG9ua3c3dXNmYzRuc24zY3VjcGNob2FqcnZzenRmaTRrbHZoYWprNSIsImF1ZCI6IkV2YWxfU0VfRm9ycmVzdEsiLCJleHAiOjE2MTYyMTM2NzgsImp0aSI6InV5Y2dmbWFncnp1aGtrdXFneDNrbWRwbHFqZGxmaGRmZHAyajV5amp1b21pcmNyZiIsImlhdCI6MTU4NDY3NzY3OCwiaXNzIjoibGlnaHRzdGVwLmNvbSJ9.aMLJRB25umnzZTeYl8gM_osa2ZqsdGYA8YqXl7d79p4
      - COLLECTOR_BABYSITTER_PORT=9000 
      - COLLECTOR_ADMIN_PLAIN_PORT=9180
      - COLLECTOR_HTTP_PLAIN_PORT=9111
      - COLLECTOR_HTTP_SECURE_PORT=9112
      - COLLECTOR_REPORTER_BYTES_PER_PROJECT=1000000000
    ports:
      - "9000:9000" #Diagnostics
      - "9180:9180" #COLLECTOR_ADMIN_PLAIN_PORT, Required for health checks
      - "9111:9111" #COLLECTOR_HTTP_PLAIN_PORT,  Unsecure traffic, or secure traffic that terminates it's secure status before it his the satellite
      - "9112:9112" #COLLECTOR_HTTP_SECURE_PORT, for Secure traffic

